### ISSUE TITLE
Make the element fit the webcomponents.org requirements and best practices

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-bottom-bar#7]
### Description
If we want to publish the element to webcomponents.org, it must fit the following requirements
https://www.webcomponents.org/publish

### Expected outcome
Output of the preview tool at https://www.webcomponents.org/preview should fit the requirements and best practices for webcomponents.org

**Comment by arpit2438735** [comment]
Here's the link as an example if you want to move forward #6 https://github.com/arpit2438735/cosmoz-bottom-bar/blob/9763ba9cfdcebc91a9fc98f02ad5c0b9d8573d69/README.md

**Comment by nomego** [comment]
Inline demo is broken in 0.9.2 since height was removed from the view.

We should probably go this route:

> Make sure your demo is responsive. Height is automatically determined, but if you need to explicitly define a minimum height you can set `height="400"` on `<custom-element-demo>`.
