### ISSUE TITLE
Never slot more than `maxToolbarItems` in toolbar

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-bottom-bar#72]
We currently slot all items in the toolbar and wait for a render to decide if they fit or needs to be moved to the menu.
However, after the introduction of `maxToolbarItems`, there could be a set limit on how many items should appear on the toolbar and there's no point waiting for renders as long as we're above that limit.
The current behavior, especially with a lot of items, creates a visually slow and unpleasant effect where the items are "sucked into" the menu on first render(s).

**Comment by cristinecula** [comment]
Let's get them to stop doing the cz-simple-action-button polka.
